// <auto-generated />
using System;
using ComandasApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComandasApi.Migrations
{
    [DbContext(typeof(ComandaDBContext))]
    [Migration("20251118230404_Categoria")]
    partial class Categoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("ComandasApi.Models.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaCardapioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCardapioId");

                    b.ToTable("CardapioItens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "que x tudo que x bacon...",
                            PossuiPreparo = true,
                            Preco = 19.90m,
                            Titulo = "X bacon"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Refrigerante geladinho",
                            PossuiPreparo = false,
                            Preco = 6.00m,
                            Titulo = "Coca cola 300ml"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Batata frita crocante",
                            PossuiPreparo = true,
                            Preco = 12.00m,
                            Titulo = "Batata frita"
                        });
                });

            modelBuilder.Entity("ComandasApi.Models.CategoriaCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrição")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriaCardapio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lanches"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bebidas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Acompanhamentos"
                        });
                });

            modelBuilder.Entity("ComandasApi.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituaçãoComanda")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Comandas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteNome = "Cliente Exemplo",
                            MesaId = 1,
                            SituaçãoComanda = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteNome = "Outro Cliente",
                            MesaId = 2,
                            SituaçãoComanda = 0
                        },
                        new
                        {
                            Id = 3,
                            ClienteNome = "Terceiro Cliente",
                            MesaId = 3,
                            SituaçãoComanda = 0
                        });
                });

            modelBuilder.Entity("ComandasApi.Models.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaItens");
                });

            modelBuilder.Entity("ComandasApi.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituaçãoMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroMesa = 1,
                            SituaçãoMesa = 0
                        },
                        new
                        {
                            Id = 2,
                            NumeroMesa = 2,
                            SituaçãoMesa = 0
                        },
                        new
                        {
                            Id = 3,
                            NumeroMesa = 3,
                            SituaçãoMesa = 0
                        });
                });

            modelBuilder.Entity("ComandasApi.Models.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituaçãoPedido")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("PedidosCozinha");
                });

            modelBuilder.Entity("ComandasApi.Models.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("PedidosCozinhaItens");
                });

            modelBuilder.Entity("ComandasApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email",
                            Nome = "admin",
                            Senha = "admin"
                        });
                });

            modelBuilder.Entity("ComandasApi.Models.reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ComandasApi.Models.CardapioItem", b =>
                {
                    b.HasOne("ComandasApi.Models.CategoriaCardapio", "CategoriaCardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CategoriaCardapioId");

                    b.Navigation("CategoriaCardapio");
                });

            modelBuilder.Entity("ComandasApi.Models.ComandaItem", b =>
                {
                    b.HasOne("ComandasApi.Models.Comanda", "Comanda")
                        .WithMany("Itens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("ComandasApi.Models.PedidoCozinha", b =>
                {
                    b.HasOne("ComandasApi.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("ComandasApi.Models.PedidoCozinhaItem", b =>
                {
                    b.HasOne("ComandasApi.Models.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComandaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComandasApi.Models.PedidoCozinha", "PedidoCozinha")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("ComandasApi.Models.CategoriaCardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComandasApi.Models.Comanda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComandasApi.Models.PedidoCozinha", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
